name: Format Code

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .